#!/usr/bin/env bash
#
# voclip Linux installer - GNOME support
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VOCLIP_PATH=""
API_KEY=""
HOTKEY="<Primary>F1"
WRAPPER_PATH="$HOME/.local/bin/voclip-run"
AUTOSTART_PATH="$HOME/.config/autostart/voclip.desktop"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# Print functions
print_step() {
    echo ""
    echo -e "${BLUE}➜${RESET} ${BOLD}$1${RESET}"
}

print_success() {
    echo -e "${GREEN}✓${RESET} $1"
}

print_error() {
    echo -e "${RED}✗${RESET} $1" >&2
}

print_warning() {
    echo -e "${YELLOW}⚠${RESET} $1"
}

print_info() {
    echo -e "${CYAN}ℹ${RESET} $1"
}

print_question() {
    echo -ne "${BOLD}$1${RESET} "
}

# Ask for API key
ask_api_key() {
    echo ""
    echo "┌─────────────────────────────────────────────────────────────┐"
    echo "│                   ${BOLD}AssemblyAI API Key${RESET}                         │"
    echo "├─────────────────────────────────────────────────────────────┤"
    echo "│ You need an API key from AssemblyAI to use voclip.         │"
    echo "│ Get one free at: https://www.assemblyai.com/               │"
    echo "└─────────────────────────────────────────────────────────────┘"
    echo ""
    print_question "Enter your AssemblyAI API key:"
    read -r API_KEY
    
    if [[ -z "$API_KEY" ]]; then
        print_error "API key cannot be empty!"
        exit 1
    fi
}

# Ask for hotkey
ask_hotkey() {
    echo ""
    echo "┌─────────────────────────────────────────────────────────────┐"
    echo "│                      ${BOLD}Keyboard Hotkey${RESET}                        │"
    echo "├─────────────────────────────────────────────────────────────┤"
    echo "│ Type the hotkey combination you want to use.               │"
    echo "│ Examples: Ctrl+F1, Super+V, Alt+Space                       │"
    echo "│ Press Enter for default: ${BOLD}Ctrl+F1${RESET}                            │"
    echo "└─────────────────────────────────────────────────────────────┘"
    echo ""
    print_question "Enter hotkey (e.g., Ctrl+F1):"
    read -r HOTKEY_INPUT
    
    if [[ -z "$HOTKEY_INPUT" ]]; then
        HOTKEY="<Primary>F1"
    else
        HOTKEY="$HOTKEY_INPUT"
        # Convert common formats
        HOTKEY="${HOTKEY//ctrl/Control}"
        HOTKEY="${HOTKEY//alt/Alt}"
        HOTKEY="${HOTKEY//super/Super}"
        HOTKEY="${HOTKEY//shift/Shift}"
    fi
    
    print_success "Using hotkey: $HOTKEY"
}

# Confirm installation
confirm_install() {
    echo ""
    echo "┌─────────────────────────────────────────────────────────────┐"
    echo "│                   ${BOLD}Installation Summary${RESET}                        │"
    echo "├─────────────────────────────────────────────────────────────┤"
    echo "│ Desktop Environment:  ${BOLD}GNOME${RESET}                              │"
    echo "│ voclip path:          ${BOLD}$VOCLIP_PATH${RESET}     │"
    echo "│ Wrapper script:       ${BOLD}$WRAPPER_PATH${RESET}│"
    echo "│ Hotkey:               ${BOLD}$HOTKEY${RESET}                            │"
    echo "│ Autostart:            ${BOLD}Enabled${RESET}                              │"
    echo "└─────────────────────────────────────────────────────────────┘"
    echo ""
    print_warning "This will create a wrapper script and register a global hotkey."
    echo ""
    read -p "Continue with installation? (Y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo "Installation cancelled."
        exit 0
    fi
}

# Create wrapper script
create_wrapper() {
    print_step "Creating wrapper script..."
    
    mkdir -p "$(dirname "$WRAPPER_PATH")"
    
    cat > "$WRAPPER_PATH" << 'WRAPPER'
#!/bin/bash
# voclip wrapper script - generated by voclip installer
# Do not edit manually - re-run installer to update

export ASSEMBLYAI_API_KEY="@API_KEY@"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export PULSE_SERVER="${PULSE_SERVER:-unix:/run/user/$(id -u)/pulse/native}"

exec /usr/local/bin/voclip "$@"
WRAPPER
    
    # Replace placeholder with actual API key
    sed -i "s|@API_KEY@|$API_KEY|g" "$WRAPPER_PATH"
    
    chmod +x "$WRAPPER_PATH"
    print_success "Created: $WRAPPER_PATH"
}

# Create desktop file for autostart
create_desktop_file() {
    print_step "Creating autostart desktop file..."
    
    mkdir -p "$(dirname "$AUTOSTART_PATH")"
    
    cat > "$AUTOSTART_PATH" << DESKTOP
[Desktop Entry]
Type=Application
Name=voclip
Comment=Voice to clipboard
Exec=$WRAPPER_PATH --update
Icon=microphone
Terminal=false
Categories=Utility;
X-GNOME-Autostart-enabled=true
DESKTOP
    
    print_success "Created: $AUTOSTART_PATH"
}

# Setup GNOME hotkey
setup_gnome_hotkey() {
    print_step "Setting up GNOME hotkey..."
    
    local CUSTOM_SCHEMA="org.gnome.settings-daemon.plugins.media-keys"
    local CUSTOM_KEYS="$CUSTOM_SCHEMA/custom-keybindings"
    local VOCLIP_KEY="org.gnome.settings-daemon.plugins.media-keys.custom-keybinding"
    
    # Get existing custom keybindings or create new list
    local EXISTING=$(gsettings get $CUSTOM_SCHEMA custom-keybindings 2>/dev/null || echo "[]")
    
    if [[ "$EXISTING" == "@as []" ]] || [[ -z "$EXISTING" ]] || [[ "$EXISTING" == "[]" ]]; then
        # Create first custom keybinding
        local KEY_PATH="$CUSTOM_KEYS/custom0"
        gsettings set $CUSTOM_KEYS "['$KEY_PATH']" 2>/dev/null || true
        
        gsettings set "$KEY_PATH" name "voclip" 2>/dev/null || true
        gsettings set "$KEY_PATH" binding "$HOTKEY" 2>/dev/null || true
        gsettings set "$KEY_PATH" command "$WRAPPER_PATH" 2>/dev/null || true
        gsettings set "$KEY_PATH" enabled true 2>/dev/null || true
        
        print_success "Hotkey registered: $HOTKEY → voclip"
    else
        # Check if voclip already exists
        local FOUND=false
        local INDEX=0
        while [[ $INDEX -lt 10 ]]; do
            local KEY_PATH="$CUSTOM_KEYS/custom$INDEX"
            local KEY_NAME=$(gsettings get "$KEY_PATH" name 2>/dev/null || echo "")
            if [[ "$KEY_NAME" == "'voclip'" ]]; then
                FOUND=true
                gsettings set "$KEY_PATH" binding "$HOTKEY" 2>/dev/null || true
                gsettings set "$KEY_PATH" command "$WRAPPER_PATH" 2>/dev/null || true
                print_success "Updated existing hotkey: $HOTKEY → voclip"
                break
            fi
            ((INDEX++))
        done
        
        if [[ "$FOUND" == "false" ]]; then
            # Add new keybinding
            local NEW_INDEX=$INDEX
            local NEW_PATH="$CUSTOM_KEYS/custom$NEW_INDEX"
            local NEW_LIST=""
            
            # Build new list
            local I=0
            while [[ $I -lt $NEW_INDEX ]]; do
                NEW_LIST="$NEW_LIST'$CUSTOM_KEYS/custom$I', "
                ((I++))
            done
            NEW_LIST="$NEW_LIST'$NEW_PATH'"
            
            gsettings set $CUSTOM_KEYS "[$NEW_LIST]" 2>/dev/null || true
            gsettings set "$NEW_PATH" name "voclip" 2>/dev/null || true
            gsettings set "$NEW_PATH" binding "$HOTKEY" 2>/dev/null || true
            gsettings set "$NEW_PATH" command "$WRAPPER_PATH" 2>/dev/null || true
            gsettings set "$NEW_PATH" enabled true 2>/dev/null || true
            
            print_success "Hotkey registered: $HOTKEY → voclip"
        fi
    fi
    
    # Also update the custom-keybindings schema to include Settings
    gsettings set $CUSTOM_SCHEMA custom-keybindings "['$CUSTOM_KEYS/custom0']" 2>/dev/null || true
}

# Finalize
finalize() {
    echo ""
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║              ${BOLD}Installation Complete!${RESET}                       ║"
    echo "╠═══════════════════════════════════════════════════════════╣"
    echo "║                                                           ║"
    echo "║  ${GREEN}✓${RESET} voclip wrapper created                               ║"
    echo "║  ${GREEN}✓${RESET} Hotkey registered ($HOTKEY)                        ║"
    echo "║  ${GREEN}✓${RESET} Autostart enabled                                   ║"
    echo "║                                                           ║"
    echo "╠═══════════════════════════════════════════════════════════╣"
    echo "║                                                           ║"
    echo "║  Usage:                                                   ║"
    echo "║    Press ${BOLD}$HOTKEY${RESET} to start voice recording          ║"
    echo "║                                                           ║"
    echo "║  Uninstall:                                               ║"
    echo "║    ./install/uninstall.sh                                 ║"
    echo "║                                                           ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo ""
}

# Main
main() {
    echo ""
    echo -e "${CYAN}╭─────────────────────────────────────────────────────────╮${RESET}"
    echo -e "${CYAN}│${RESET}           ${BOLD}voclip Linux Installer${RESET} (GNOME)              ${CYAN}│${RESET}"
    echo -e "${CYAN}╰─────────────────────────────────────────────────────────╯${RESET}"
    
    # Find voclip
    print_step "Finding voclip binary..."
    for path in \
        "$(which voclip 2>/dev/null)" \
        "$HOME/.cargo/bin/voclip" \
        "$HOME/.local/bin/voclip" \
        "/usr/local/bin/voclip" \
        "/usr/bin/voclip"
    do
        if [[ -x "$path" ]]; then
            VOCLIP_PATH="$path"
            break
        fi
    done
    
    if [[ -z "$VOCLIP_PATH" ]]; then
        print_error "voclip not found!"
        echo ""
        echo "Please install voclip first:"
        echo "  cargo install voclip"
        echo ""
        echo "Or download from:"
        echo "  https://github.com/iceman1010/voclip/releases"
        exit 1
    fi
    print_success "Found: $VOCLIP_PATH"
    
    # Update wrapper to use found path
    WRAPPER_PATH="$HOME/.local/bin/voclip-run"
    
    # Interactive setup
    ask_api_key
    ask_hotkey
    confirm_install
    
    # Install
    create_wrapper
    create_desktop_file
    setup_gnome_hotkey
    finalize
}

main "$@"
